Validator is off when MODE is not PROD
openimis/openimis-be-core_py pull request #296
Opened 2024-05-21 17:43 UTC by lruzicki

Password Validator is off when MODE is not PROD

2024-05-22 10:00 UTC, delcroip requested changes
please transform that into a valid AUTH_PASSWORD_VALIDATORS

2024-05-23 13:00 UTC, lruzicki commented
> please transform that into a valid AUTH_PASSWORD_VALIDATORS

@delcroip thanks for advice, I did change it. Take a look

2024-05-23 13:25 UTC, delcroip commented on core/utils.py
> +                    f"{settings.PASSWORD_SYMBOLS} special character(s)."
that should avoid code duplications

```suggestion
                    self.get_help_text()
```

2024-05-24 14:50 UTC, delcroip commented on setup.py
>      ],
```suggestion
        'password-validator',
        'zxcvbn'
    ],
```

2024-05-27 11:42 UTC, delcroip approved these changes

2024-05-27 11:43 UTC, merged